imports:

# Content
- path: github.com/hugolify/hugolify-theme-projects
- path: github.com/hugolify/hugolify-theme-posts-categories
- path: github.com/hugolify/hugolify-theme-posts

# Core theme required
- path: github.com/hugolify/hugolify-theme

# CMS
- path: github.com/hugolify/hugolify-admin
